--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- account_bounce_block_dto class
local account_bounce_block_dto = {}
local account_bounce_block_dto_mt = {
	__name = "account_bounce_block_dto";
	__index = account_bounce_block_dto;
}

local function cast_account_bounce_block_dto(t)
	return setmetatable(t, account_bounce_block_dto_mt)
end

local function new_account_bounce_block_dto(is_frozen, is_sending_blocked, bounce_count, bounce_count_today, maximum_daily_bounces, maximum_account_bounces)
	return cast_account_bounce_block_dto({
		["isFrozen"] = is_frozen;
		["isSendingBlocked"] = is_sending_blocked;
		["bounceCount"] = bounce_count;
		["bounceCountToday"] = bounce_count_today;
		["maximumDailyBounces"] = maximum_daily_bounces;
		["maximumAccountBounces"] = maximum_account_bounces;
	})
end

return {
	cast = cast_account_bounce_block_dto;
	new = new_account_bounce_block_dto;
}
