--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- alias_dto class
local alias_dto = {}
local alias_dto_mt = {
	__name = "alias_dto";
	__index = alias_dto;
}

local function cast_alias_dto(t)
	return setmetatable(t, alias_dto_mt)
end

local function new_alias_dto(created_at, email_address, id, inbox_id, is_verified, masked_email_address, name, updated_at, use_threads, user_id)
	return cast_alias_dto({
		["createdAt"] = created_at;
		["emailAddress"] = email_address;
		["id"] = id;
		["inboxId"] = inbox_id;
		["isVerified"] = is_verified;
		["maskedEmailAddress"] = masked_email_address;
		["name"] = name;
		["updatedAt"] = updated_at;
		["useThreads"] = use_threads;
		["userId"] = user_id;
	})
end

return {
	cast = cast_alias_dto;
	new = new_alias_dto;
}
