--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- audit_log_search_options class
local audit_log_search_options = {}
local audit_log_search_options_mt = {
	__name = "audit_log_search_options";
	__index = audit_log_search_options;
}

local function cast_audit_log_search_options(t)
	return setmetatable(t, audit_log_search_options_mt)
end

local function new_audit_log_search_options(since, before, action, user_id, actor_user_id, target_user_id, resource_type, resource_id, outcome, request_id, ip_address, event_id, page_size, cursor)
	return cast_audit_log_search_options({
		["since"] = since;
		["before"] = before;
		["action"] = action;
		["userId"] = user_id;
		["actorUserId"] = actor_user_id;
		["targetUserId"] = target_user_id;
		["resourceType"] = resource_type;
		["resourceId"] = resource_id;
		["outcome"] = outcome;
		["requestId"] = request_id;
		["ipAddress"] = ip_address;
		["eventId"] = event_id;
		["pageSize"] = page_size;
		["cursor"] = cursor;
	})
end

return {
	cast = cast_audit_log_search_options;
	new = new_audit_log_search_options;
}
