--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- bulk_send_email_options class
local bulk_send_email_options = {}
local bulk_send_email_options_mt = {
	__name = "bulk_send_email_options";
	__index = bulk_send_email_options;
}

local function cast_bulk_send_email_options(t)
	return setmetatable(t, bulk_send_email_options_mt)
end

local function new_bulk_send_email_options(inbox_ids, send_email_options)
	return cast_bulk_send_email_options({
		["inboxIds"] = inbox_ids;
		["sendEmailOptions"] = send_email_options;
	})
end

return {
	cast = cast_bulk_send_email_options;
	new = new_bulk_send_email_options;
}
