--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- campaign_probe_dto class
local campaign_probe_dto = {}
local campaign_probe_dto_mt = {
	__name = "campaign_probe_dto";
	__index = campaign_probe_dto;
}

local function cast_campaign_probe_dto(t)
	return setmetatable(t, campaign_probe_dto_mt)
end

local function new_campaign_probe_dto(id, user_id, name, local_part, email_address, enabled, interval_seconds, scheduling_enabled, next_run_at, last_run_status, last_health_score, last_ingest_at, total_ingest_count, created_at, updated_at)
	return cast_campaign_probe_dto({
		["id"] = id;
		["userId"] = user_id;
		["name"] = name;
		["localPart"] = local_part;
		["emailAddress"] = email_address;
		["enabled"] = enabled;
		["intervalSeconds"] = interval_seconds;
		["schedulingEnabled"] = scheduling_enabled;
		["nextRunAt"] = next_run_at;
		["lastRunStatus"] = last_run_status;
		["lastHealthScore"] = last_health_score;
		["lastIngestAt"] = last_ingest_at;
		["totalIngestCount"] = total_ingest_count;
		["createdAt"] = created_at;
		["updatedAt"] = updated_at;
	})
end

return {
	cast = cast_campaign_probe_dto;
	new = new_campaign_probe_dto;
}
