--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- code_candidate class
local code_candidate = {}
local code_candidate_mt = {
	__name = "code_candidate";
	__index = code_candidate;
}

local function cast_code_candidate(t)
	return setmetatable(t, code_candidate_mt)
end

local function new_code_candidate(code, confidence, method, source, context)
	return cast_code_candidate({
		["code"] = code;
		["confidence"] = confidence;
		["method"] = method;
		["source"] = source;
		["context"] = context;
	})
end

return {
	cast = cast_code_candidate;
	new = new_code_candidate;
}
