--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- connector_provider_settings_dto class
local connector_provider_settings_dto = {}
local connector_provider_settings_dto_mt = {
	__name = "connector_provider_settings_dto";
	__index = connector_provider_settings_dto;
}

local function cast_connector_provider_settings_dto(t)
	return setmetatable(t, connector_provider_settings_dto_mt)
end

local function new_connector_provider_settings_dto(google_settings, microsoft_settings)
	return cast_connector_provider_settings_dto({
		["googleSettings"] = google_settings;
		["microsoftSettings"] = microsoft_settings;
	})
end

return {
	cast = cast_connector_provider_settings_dto;
	new = new_connector_provider_settings_dto;
}
