--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- contact_dto class
local contact_dto = {}
local contact_dto_mt = {
	__name = "contact_dto";
	__index = contact_dto;
}

local function cast_contact_dto(t)
	return setmetatable(t, contact_dto_mt)
end

local function new_contact_dto(id, group_id, first_name, last_name, company, email_addresses, primary_email_address, tags, meta_data, opt_out, created_at)
	return cast_contact_dto({
		["id"] = id;
		["groupId"] = group_id;
		["firstName"] = first_name;
		["lastName"] = last_name;
		["company"] = company;
		["emailAddresses"] = email_addresses;
		["primaryEmailAddress"] = primary_email_address;
		["tags"] = tags;
		["metaData"] = meta_data;
		["optOut"] = opt_out;
		["createdAt"] = created_at;
	})
end

return {
	cast = cast_contact_dto;
	new = new_contact_dto;
}
