--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_email_audit_options class
local create_email_audit_options = {}
local create_email_audit_options_mt = {
	__name = "create_email_audit_options";
	__index = create_email_audit_options;
}

local function cast_create_email_audit_options(t)
	return setmetatable(t, create_email_audit_options_mt)
end

local function new_create_email_audit_options(from_address, recipient, subject, html_body, text_body, email_analysis, has_attachments)
	return cast_create_email_audit_options({
		["fromAddress"] = from_address;
		["recipient"] = recipient;
		["subject"] = subject;
		["htmlBody"] = html_body;
		["textBody"] = text_body;
		["emailAnalysis"] = email_analysis;
		["hasAttachments"] = has_attachments;
	})
end

return {
	cast = cast_create_email_audit_options;
	new = new_create_email_audit_options;
}
