--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_totp_device_otp_auth_url_options class
local create_totp_device_otp_auth_url_options = {}
local create_totp_device_otp_auth_url_options_mt = {
	__name = "create_totp_device_otp_auth_url_options";
	__index = create_totp_device_otp_auth_url_options;
}

local function cast_create_totp_device_otp_auth_url_options(t)
	return setmetatable(t, create_totp_device_otp_auth_url_options_mt)
end

local function new_create_totp_device_otp_auth_url_options(otp_auth_url, name, username, issuer, digits, period, algorithm)
	return cast_create_totp_device_otp_auth_url_options({
		["otpAuthUrl"] = otp_auth_url;
		["name"] = name;
		["username"] = username;
		["issuer"] = issuer;
		["digits"] = digits;
		["period"] = period;
		["algorithm"] = algorithm;
	})
end

return {
	cast = cast_create_totp_device_otp_auth_url_options;
	new = new_create_totp_device_otp_auth_url_options;
}
