--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.   ## Resources - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- create_contact_options class
local create_contact_options = {}
local create_contact_options_mt = {
	__name = "create_contact_options";
	__index = create_contact_options;
}

local function cast_create_contact_options(t)
	return setmetatable(t, create_contact_options_mt)
end

local function new_create_contact_options(email_addresses, first_name, group_id, meta_data, opt_out, tags, last_name, company)
	return cast_create_contact_options({
		["emailAddresses"] = email_addresses;
		["firstName"] = first_name;
		["groupId"] = group_id;
		["metaData"] = meta_data;
		["optOut"] = opt_out;
		["tags"] = tags;
		["lastName"] = last_name;
		["company"] = company;
	})
end

return {
	cast = cast_create_contact_options;
	new = new_create_contact_options;
}
