--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_deliverability_test_options class
local create_deliverability_test_options = {}
local create_deliverability_test_options_mt = {
	__name = "create_deliverability_test_options";
	__index = create_deliverability_test_options;
}

local function cast_create_deliverability_test_options(t)
	return setmetatable(t, create_deliverability_test_options_mt)
end

local function new_create_deliverability_test_options(name, description, scope, start_at, max_duration_seconds, success_threshold_percent, selector, expectations)
	return cast_create_deliverability_test_options({
		["name"] = name;
		["description"] = description;
		["scope"] = scope;
		["startAt"] = start_at;
		["maxDurationSeconds"] = max_duration_seconds;
		["successThresholdPercent"] = success_threshold_percent;
		["selector"] = selector;
		["expectations"] = expectations;
	})
end

return {
	cast = cast_create_deliverability_test_options;
	new = new_create_deliverability_test_options;
}
