--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_alias_options class
local create_alias_options = {}
local create_alias_options_mt = {
	__name = "create_alias_options";
	__index = create_alias_options;
}

local function cast_create_alias_options(t)
	return setmetatable(t, create_alias_options_mt)
end

local function new_create_alias_options(email_address, inbox_id, name, use_threads, domain_id, verify_email_address)
	return cast_create_alias_options({
		["emailAddress"] = email_address;
		["inboxId"] = inbox_id;
		["name"] = name;
		["useThreads"] = use_threads;
		["domainId"] = domain_id;
		["verifyEmailAddress"] = verify_email_address;
	})
end

return {
	cast = cast_create_alias_options;
	new = new_create_alias_options;
}
