--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_domain_options class
local create_domain_options = {}
local create_domain_options_mt = {
	__name = "create_domain_options";
	__index = create_domain_options;
}

local function cast_create_domain_options(t)
	return setmetatable(t, create_domain_options_mt)
end

local function new_create_domain_options(domain, description, created_catch_all_inbox, domain_type)
	return cast_create_domain_options({
		["domain"] = domain;
		["description"] = description;
		["createdCatchAllInbox"] = created_catch_all_inbox;
		["domainType"] = domain_type;
	})
end

return {
	cast = cast_create_domain_options;
	new = new_create_domain_options;
}
