--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_webhook_options class
local create_webhook_options = {}
local create_webhook_options_mt = {
	__name = "create_webhook_options";
	__index = create_webhook_options;
}

local function cast_create_webhook_options(t)
	return setmetatable(t, create_webhook_options_mt)
end

local function new_create_webhook_options(url, basic_auth, name, event_name, include_headers, request_body_template, ai_transform_id, use_static_ip_range, ignore_insecure_ssl_certificates, tags)
	return cast_create_webhook_options({
		["url"] = url;
		["basicAuth"] = basic_auth;
		["name"] = name;
		["eventName"] = event_name;
		["includeHeaders"] = include_headers;
		["requestBodyTemplate"] = request_body_template;
		["aiTransformId"] = ai_transform_id;
		["useStaticIpRange"] = use_static_ip_range;
		["ignoreInsecureSslCertificates"] = ignore_insecure_ssl_certificates;
		["tags"] = tags;
	})
end

return {
	cast = cast_create_webhook_options;
	new = new_create_webhook_options;
}
