--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- create_domain_monitor_options class
local create_domain_monitor_options = {}
local create_domain_monitor_options_mt = {
	__name = "create_domain_monitor_options";
	__index = create_domain_monitor_options;
}

local function cast_create_domain_monitor_options(t)
	return setmetatable(t, create_domain_monitor_options_mt)
end

local function new_create_domain_monitor_options(domain, name, interval_seconds, enabled, scheduling_enabled)
	return cast_create_domain_monitor_options({
		["domain"] = domain;
		["name"] = name;
		["intervalSeconds"] = interval_seconds;
		["enabled"] = enabled;
		["schedulingEnabled"] = scheduling_enabled;
	})
end

return {
	cast = cast_create_domain_monitor_options;
	new = new_create_domain_monitor_options;
}
