--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- deliverability_expectation class
local deliverability_expectation = {}
local deliverability_expectation_mt = {
	__name = "deliverability_expectation";
	__index = deliverability_expectation;
}

local function cast_deliverability_expectation(t)
	return setmetatable(t, deliverability_expectation_mt)
end

local function new_deliverability_expectation(name, min_count, from, to, subject)
	return cast_deliverability_expectation({
		["name"] = name;
		["minCount"] = min_count;
		["from"] = from;
		["to"] = to;
		["subject"] = subject;
	})
end

return {
	cast = cast_deliverability_expectation;
	new = new_deliverability_expectation;
}
