--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- deliverability_selector_options class
local deliverability_selector_options = {}
local deliverability_selector_options_mt = {
	__name = "deliverability_selector_options";
	__index = deliverability_selector_options;
}

local function cast_deliverability_selector_options(t)
	return setmetatable(t, deliverability_selector_options_mt)
end

local function new_deliverability_selector_options(type, pattern, phone_country, entity_ids, exclude_entity_ids)
	return cast_deliverability_selector_options({
		["type"] = type;
		["pattern"] = pattern;
		["phoneCountry"] = phone_country;
		["entityIds"] = entity_ids;
		["excludeEntityIds"] = exclude_entity_ids;
	})
end

return {
	cast = cast_deliverability_selector_options;
	new = new_deliverability_selector_options;
}
