--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- device_preview_screenshot_dto class
local device_preview_screenshot_dto = {}
local device_preview_screenshot_dto_mt = {
	__name = "device_preview_screenshot_dto";
	__index = device_preview_screenshot_dto;
}

local function cast_device_preview_screenshot_dto(t)
	return setmetatable(t, device_preview_screenshot_dto_mt)
end

local function new_device_preview_screenshot_dto(screenshot_id, run_id, target_id, variant, title, description, is_primary, display_order, storage_key, access_url, live_view_url, session_id, browser_context_id, deep_link_url, width, height, created_at, updated_at)
	return cast_device_preview_screenshot_dto({
		["screenshotId"] = screenshot_id;
		["runId"] = run_id;
		["targetId"] = target_id;
		["variant"] = variant;
		["title"] = title;
		["description"] = description;
		["isPrimary"] = is_primary;
		["displayOrder"] = display_order;
		["storageKey"] = storage_key;
		["accessUrl"] = access_url;
		["liveViewUrl"] = live_view_url;
		["sessionId"] = session_id;
		["browserContextId"] = browser_context_id;
		["deepLinkUrl"] = deep_link_url;
		["width"] = width;
		["height"] = height;
		["createdAt"] = created_at;
		["updatedAt"] = updated_at;
	})
end

return {
	cast = cast_device_preview_screenshot_dto;
	new = new_device_preview_screenshot_dto;
}
