--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- dmarc_report_source_summary class
local dmarc_report_source_summary = {}
local dmarc_report_source_summary_mt = {
	__name = "dmarc_report_source_summary";
	__index = dmarc_report_source_summary;
}

local function cast_dmarc_report_source_summary(t)
	return setmetatable(t, dmarc_report_source_summary_mt)
end

local function new_dmarc_report_source_summary(source_ip, count, disposition, dkim_aligned, spf_aligned, header_from)
	return cast_dmarc_report_source_summary({
		["sourceIp"] = source_ip;
		["count"] = count;
		["disposition"] = disposition;
		["dkimAligned"] = dkim_aligned;
		["spfAligned"] = spf_aligned;
		["headerFrom"] = header_from;
	})
end

return {
	cast = cast_dmarc_report_source_summary;
	new = new_dmarc_report_source_summary;
}
