--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- domain_monitor_run_dto class
local domain_monitor_run_dto = {}
local domain_monitor_run_dto_mt = {
	__name = "domain_monitor_run_dto";
	__index = domain_monitor_run_dto;
}

local function cast_domain_monitor_run_dto(t)
	return setmetatable(t, domain_monitor_run_dto_mt)
end

local function new_domain_monitor_run_dto(id, monitor_id, user_id, domain, status, trigger_source, health_score, total_checks, passing_checks, failing_checks, spf_ok, dmarc_ok, dmarc_enforced, mx_ok, insights, error_message, created_at, updated_at)
	return cast_domain_monitor_run_dto({
		["id"] = id;
		["monitorId"] = monitor_id;
		["userId"] = user_id;
		["domain"] = domain;
		["status"] = status;
		["triggerSource"] = trigger_source;
		["healthScore"] = health_score;
		["totalChecks"] = total_checks;
		["passingChecks"] = passing_checks;
		["failingChecks"] = failing_checks;
		["spfOk"] = spf_ok;
		["dmarcOk"] = dmarc_ok;
		["dmarcEnforced"] = dmarc_enforced;
		["mxOk"] = mx_ok;
		["insights"] = insights;
		["errorMessage"] = error_message;
		["createdAt"] = created_at;
		["updatedAt"] = updated_at;
	})
end

return {
	cast = cast_domain_monitor_run_dto;
	new = new_domain_monitor_run_dto;
}
