--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- email_preview class
local email_preview = {}
local email_preview_mt = {
	__name = "email_preview";
	__index = email_preview;
}

local function cast_email_preview(t)
	return setmetatable(t, email_preview_mt)
end

local function new_email_preview(id, inbox_id, domain_id, subject, to, from, bcc, cc, created_at, read, attachments, thread_id, message_id, in_reply_to, sender, recipients, favourite, body_part_content_types, plus_address, size_bytes)
	return cast_email_preview({
		["id"] = id;
		["inboxId"] = inbox_id;
		["domainId"] = domain_id;
		["subject"] = subject;
		["to"] = to;
		["from"] = from;
		["bcc"] = bcc;
		["cc"] = cc;
		["createdAt"] = created_at;
		["read"] = read;
		["attachments"] = attachments;
		["threadId"] = thread_id;
		["messageId"] = message_id;
		["inReplyTo"] = in_reply_to;
		["sender"] = sender;
		["recipients"] = recipients;
		["favourite"] = favourite;
		["bodyPartContentTypes"] = body_part_content_types;
		["plusAddress"] = plus_address;
		["sizeBytes"] = size_bytes;
	})
end

return {
	cast = cast_email_preview;
	new = new_email_preview;
}
