--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- email_signature class
local email_signature = {}
local email_signature_mt = {
	__name = "email_signature";
	__index = email_signature;
}

local function cast_email_signature(t)
	return setmetatable(t, email_signature_mt)
end

local function new_email_signature(body, source, marker, detection_type)
	return cast_email_signature({
		["body"] = body;
		["source"] = source;
		["marker"] = marker;
		["detectionType"] = detection_type;
	})
end

return {
	cast = cast_email_signature;
	new = new_email_signature;
}
