--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- email_intelligence_score_breakdown_dto class
local email_intelligence_score_breakdown_dto = {}
local email_intelligence_score_breakdown_dto_mt = {
	__name = "email_intelligence_score_breakdown_dto";
	__index = email_intelligence_score_breakdown_dto;
}

local function cast_email_intelligence_score_breakdown_dto(t)
	return setmetatable(t, email_intelligence_score_breakdown_dto_mt)
end

local function new_email_intelligence_score_breakdown_dto(randomness_penalty, free_provider_penalty, https_website_penalty, dns_penalty, domain_age_penalty, email_validation_penalty, total_penalty)
	return cast_email_intelligence_score_breakdown_dto({
		["randomnessPenalty"] = randomness_penalty;
		["freeProviderPenalty"] = free_provider_penalty;
		["httpsWebsitePenalty"] = https_website_penalty;
		["dnsPenalty"] = dns_penalty;
		["domainAgePenalty"] = domain_age_penalty;
		["emailValidationPenalty"] = email_validation_penalty;
		["totalPenalty"] = total_penalty;
	})
end

return {
	cast = cast_email_intelligence_score_breakdown_dto;
	new = new_email_intelligence_score_breakdown_dto;
}
