--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- email_projection class
local email_projection = {}
local email_projection_mt = {
	__name = "email_projection";
	__index = email_projection;
}

local function cast_email_projection(t)
	return setmetatable(t, email_projection_mt)
end

local function new_email_projection(attachments, bcc, body_md5_hash, cc, created_at, from, id, inbox_id, read, subject, team_access, to)
	return cast_email_projection({
		["attachments"] = attachments;
		["bcc"] = bcc;
		["bodyMD5Hash"] = body_md5_hash;
		["cc"] = cc;
		["createdAt"] = created_at;
		["from"] = from;
		["id"] = id;
		["inboxId"] = inbox_id;
		["read"] = read;
		["subject"] = subject;
		["teamAccess"] = team_access;
		["to"] = to;
	})
end

return {
	cast = cast_email_projection;
	new = new_email_projection;
}
