--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- email_audit_comparison_dto class
local email_audit_comparison_dto = {}
local email_audit_comparison_dto_mt = {
	__name = "email_audit_comparison_dto";
	__index = email_audit_comparison_dto;
}

local function cast_email_audit_comparison_dto(t)
	return setmetatable(t, email_audit_comparison_dto_mt)
end

local function new_email_audit_comparison_dto(baseline, current, health_score_delta, status_changed, broken_link_delta, broken_image_delta, spelling_issue_delta, html_error_delta, html_warning_delta, compatibility_warning_delta, compatibility_not_supported_delta, reputation_failure_delta, attachment_mention_issue_delta, added_insights, removed_insights)
	return cast_email_audit_comparison_dto({
		["baseline"] = baseline;
		["current"] = current;
		["healthScoreDelta"] = health_score_delta;
		["statusChanged"] = status_changed;
		["brokenLinkDelta"] = broken_link_delta;
		["brokenImageDelta"] = broken_image_delta;
		["spellingIssueDelta"] = spelling_issue_delta;
		["htmlErrorDelta"] = html_error_delta;
		["htmlWarningDelta"] = html_warning_delta;
		["compatibilityWarningDelta"] = compatibility_warning_delta;
		["compatibilityNotSupportedDelta"] = compatibility_not_supported_delta;
		["reputationFailureDelta"] = reputation_failure_delta;
		["attachmentMentionIssueDelta"] = attachment_mention_issue_delta;
		["addedInsights"] = added_insights;
		["removedInsights"] = removed_insights;
	})
end

return {
	cast = cast_email_audit_comparison_dto;
	new = new_email_audit_comparison_dto;
}
