--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- export_transformer_response class
local export_transformer_response = {}
local export_transformer_response_mt = {
	__name = "export_transformer_response";
	__index = export_transformer_response;
}

local function cast_export_transformer_response(t)
	return setmetatable(t, export_transformer_response_mt)
end

local function new_export_transformer_response(job_id, status)
	return cast_export_transformer_response({
		["jobId"] = job_id;
		["status"] = status;
	})
end

return {
	cast = cast_export_transformer_response;
	new = new_export_transformer_response;
}
