--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- export_transformer_options class
local export_transformer_options = {}
local export_transformer_options_mt = {
	__name = "export_transformer_options";
	__index = export_transformer_options;
}

local function cast_export_transformer_options(t)
	return setmetatable(t, export_transformer_options_mt)
end

local function new_export_transformer_options(ai_transform_id, ai_mapping_id, flatten_arrays, since, before, format, inbox_id, phone_id, email_id, sms_id, attachment_id, include_meta_data, delimiter, array_separator, include_meta_data_columns)
	return cast_export_transformer_options({
		["aiTransformId"] = ai_transform_id;
		["aiMappingId"] = ai_mapping_id;
		["flattenArrays"] = flatten_arrays;
		["since"] = since;
		["before"] = before;
		["format"] = format;
		["inboxId"] = inbox_id;
		["phoneId"] = phone_id;
		["emailId"] = email_id;
		["smsId"] = sms_id;
		["attachmentId"] = attachment_id;
		["includeMetaData"] = include_meta_data;
		["delimiter"] = delimiter;
		["arraySeparator"] = array_separator;
		["includeMetaDataColumns"] = include_meta_data_columns;
	})
end

return {
	cast = cast_export_transformer_options;
	new = new_export_transformer_options;
}
