--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- guest_portal_user_create_dto class
local guest_portal_user_create_dto = {}
local guest_portal_user_create_dto_mt = {
	__name = "guest_portal_user_create_dto";
	__index = guest_portal_user_create_dto;
}

local function cast_guest_portal_user_create_dto(t)
	return setmetatable(t, guest_portal_user_create_dto_mt)
end

local function new_guest_portal_user_create_dto(guest, password)
	return cast_guest_portal_user_create_dto({
		["guest"] = guest;
		["password"] = password;
	})
end

return {
	cast = cast_guest_portal_user_create_dto;
	new = new_guest_portal_user_create_dto;
}
