--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- guest_portal_user_projection class
local guest_portal_user_projection = {}
local guest_portal_user_projection_mt = {
	__name = "guest_portal_user_projection";
	__index = guest_portal_user_projection;
}

local function cast_guest_portal_user_projection(t)
	return setmetatable(t, guest_portal_user_projection_mt)
end

local function new_guest_portal_user_projection(created_at, updated_at, user_id, email_address, inbox_id, portal_id, name, id, username)
	return cast_guest_portal_user_projection({
		["createdAt"] = created_at;
		["updatedAt"] = updated_at;
		["userId"] = user_id;
		["emailAddress"] = email_address;
		["inboxId"] = inbox_id;
		["portalId"] = portal_id;
		["name"] = name;
		["id"] = id;
		["username"] = username;
	})
end

return {
	cast = cast_guest_portal_user_projection;
	new = new_guest_portal_user_projection;
}
