--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- imap_smtp_access_details class
local imap_smtp_access_details = {}
local imap_smtp_access_details_mt = {
	__name = "imap_smtp_access_details";
	__index = imap_smtp_access_details;
}

local function cast_imap_smtp_access_details(t)
	return setmetatable(t, imap_smtp_access_details_mt)
end

local function new_imap_smtp_access_details(smtp_server_host, smtp_server_port, smtp_username, smtp_password, imap_server_host, imap_server_port, imap_username, imap_password)
	return cast_imap_smtp_access_details({
		["smtpServerHost"] = smtp_server_host;
		["smtpServerPort"] = smtp_server_port;
		["smtpUsername"] = smtp_username;
		["smtpPassword"] = smtp_password;
		["imapServerHost"] = imap_server_host;
		["imapServerPort"] = imap_server_port;
		["imapUsername"] = imap_username;
		["imapPassword"] = imap_password;
	})
end

return {
	cast = cast_imap_smtp_access_details;
	new = new_imap_smtp_access_details;
}
