--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- imap_server_fetch_item class
local imap_server_fetch_item = {}
local imap_server_fetch_item_mt = {
	__name = "imap_server_fetch_item";
	__index = imap_server_fetch_item;
}

local function cast_imap_server_fetch_item(t)
	return setmetatable(t, imap_server_fetch_item_mt)
end

local function new_imap_server_fetch_item(content, id, uid, seq_num, read)
	return cast_imap_server_fetch_item({
		["content"] = content;
		["id"] = id;
		["uid"] = uid;
		["seqNum"] = seq_num;
		["read"] = read;
	})
end

return {
	cast = cast_imap_server_fetch_item;
	new = new_imap_server_fetch_item;
}
