--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- inbox_ruleset_dto class
local inbox_ruleset_dto = {}
local inbox_ruleset_dto_mt = {
	__name = "inbox_ruleset_dto";
	__index = inbox_ruleset_dto;
}

local function cast_inbox_ruleset_dto(t)
	return setmetatable(t, inbox_ruleset_dto_mt)
end

local function new_inbox_ruleset_dto(id, inbox_id, scope, action, target, handler, created_at)
	return cast_inbox_ruleset_dto({
		["id"] = id;
		["inboxId"] = inbox_id;
		["scope"] = scope;
		["action"] = action;
		["target"] = target;
		["handler"] = handler;
		["createdAt"] = created_at;
	})
end

return {
	cast = cast_inbox_ruleset_dto;
	new = new_inbox_ruleset_dto;
}
