--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- match_option class
local match_option = {}
local match_option_mt = {
	__name = "match_option";
	__index = match_option;
}

local function cast_match_option(t)
	return setmetatable(t, match_option_mt)
end

local function new_match_option(field, should, value)
	return cast_match_option({
		["field"] = field;
		["should"] = should;
		["value"] = value;
	})
end

return {
	cast = cast_match_option;
	new = new_match_option;
}
