--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- missed_sms_dto class
local missed_sms_dto = {}
local missed_sms_dto_mt = {
	__name = "missed_sms_dto";
	__index = missed_sms_dto;
}

local function cast_missed_sms_dto(t)
	return setmetatable(t, missed_sms_dto_mt)
end

local function new_missed_sms_dto(id, user_id, phone_number, from_number, to_number, body, sid, created_at, updated_at)
	return cast_missed_sms_dto({
		["id"] = id;
		["userId"] = user_id;
		["phoneNumber"] = phone_number;
		["fromNumber"] = from_number;
		["toNumber"] = to_number;
		["body"] = body;
		["sid"] = sid;
		["createdAt"] = created_at;
		["updatedAt"] = updated_at;
	})
end

return {
	cast = cast_missed_sms_dto;
	new = new_missed_sms_dto;
}
