--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- phone_pool_member_dto class
local phone_pool_member_dto = {}
local phone_pool_member_dto_mt = {
	__name = "phone_pool_member_dto";
	__index = phone_pool_member_dto;
}

local function cast_phone_pool_member_dto(t)
	return setmetatable(t, phone_pool_member_dto_mt)
end

local function new_phone_pool_member_dto(id, pool_id, phone_number_id, phone_number, phone_country, phone_name, created_at, active_lease)
	return cast_phone_pool_member_dto({
		["id"] = id;
		["poolId"] = pool_id;
		["phoneNumberId"] = phone_number_id;
		["phoneNumber"] = phone_number;
		["phoneCountry"] = phone_country;
		["phoneName"] = phone_name;
		["createdAt"] = created_at;
		["activeLease"] = active_lease;
	})
end

return {
	cast = cast_phone_pool_member_dto;
	new = new_phone_pool_member_dto;
}
