--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- phone_number_release_projection class
local phone_number_release_projection = {}
local phone_number_release_projection_mt = {
	__name = "phone_number_release_projection";
	__index = phone_number_release_projection;
}

local function cast_phone_number_release_projection(t)
	return setmetatable(t, phone_number_release_projection_mt)
end

local function new_phone_number_release_projection(user_id, created_at, phone_country, phone_number, subscription_schedule, plan_currency, name, id)
	return cast_phone_number_release_projection({
		["userId"] = user_id;
		["createdAt"] = created_at;
		["phoneCountry"] = phone_country;
		["phoneNumber"] = phone_number;
		["subscriptionSchedule"] = subscription_schedule;
		["planCurrency"] = plan_currency;
		["name"] = name;
		["id"] = id;
	})
end

return {
	cast = cast_phone_number_release_projection;
	new = new_phone_number_release_projection;
}
