--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- reply_for_sms class
local reply_for_sms = {}
local reply_for_sms_mt = {
	__name = "reply_for_sms";
	__index = reply_for_sms;
}

local function cast_reply_for_sms(t)
	return setmetatable(t, reply_for_sms_mt)
end

local function new_reply_for_sms(reply)
	return cast_reply_for_sms({
		["reply"] = reply;
	})
end

return {
	cast = cast_reply_for_sms;
	new = new_reply_for_sms;
}
