--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- search_emails_options class
local search_emails_options = {}
local search_emails_options_mt = {
	__name = "search_emails_options";
	__index = search_emails_options;
}

local function cast_search_emails_options(t)
	return setmetatable(t, search_emails_options_mt)
end

local function new_search_emails_options(inbox_ids, page_index, page_size, sort_direction, unread_only, search_filter, since, before)
	return cast_search_emails_options({
		["inboxIds"] = inbox_ids;
		["pageIndex"] = page_index;
		["pageSize"] = page_size;
		["sortDirection"] = sort_direction;
		["unreadOnly"] = unread_only;
		["searchFilter"] = search_filter;
		["since"] = since;
		["before"] = before;
	})
end

return {
	cast = cast_search_emails_options;
	new = new_search_emails_options;
}
