--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- send_email_options class
local send_email_options = {}
local send_email_options_mt = {
	__name = "send_email_options";
	__index = send_email_options;
}

local function cast_send_email_options(t)
	return setmetatable(t, send_email_options_mt)
end

local function new_send_email_options(attachments, bcc, body, cc, charset, from, is_html, reply_to, send_strategy, subject, template, template_variables, to, to_contacts, to_group)
	return cast_send_email_options({
		["attachments"] = attachments;
		["bcc"] = bcc;
		["body"] = body;
		["cc"] = cc;
		["charset"] = charset;
		["from"] = from;
		["isHTML"] = is_html;
		["replyTo"] = reply_to;
		["sendStrategy"] = send_strategy;
		["subject"] = subject;
		["template"] = template;
		["templateVariables"] = template_variables;
		["to"] = to;
		["toContacts"] = to_contacts;
		["toGroup"] = to_group;
	})
end

return {
	cast = cast_send_email_options;
	new = new_send_email_options;
}
