--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- smtp_access_details class
local smtp_access_details = {}
local smtp_access_details_mt = {
	__name = "smtp_access_details";
	__index = smtp_access_details;
}

local function cast_smtp_access_details(t)
	return setmetatable(t, smtp_access_details_mt)
end

local function new_smtp_access_details(secure_smtp_server_host, secure_smtp_server_port, secure_smtp_username, secure_smtp_password, smtp_server_host, smtp_server_port, smtp_username, smtp_password, mail_from_domain)
	return cast_smtp_access_details({
		["secureSmtpServerHost"] = secure_smtp_server_host;
		["secureSmtpServerPort"] = secure_smtp_server_port;
		["secureSmtpUsername"] = secure_smtp_username;
		["secureSmtpPassword"] = secure_smtp_password;
		["smtpServerHost"] = smtp_server_host;
		["smtpServerPort"] = smtp_server_port;
		["smtpUsername"] = smtp_username;
		["smtpPassword"] = smtp_password;
		["mailFromDomain"] = mail_from_domain;
	})
end

return {
	cast = cast_smtp_access_details;
	new = new_smtp_access_details;
}
