--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- tenant_reputation_finding_dto class
local tenant_reputation_finding_dto = {}
local tenant_reputation_finding_dto_mt = {
	__name = "tenant_reputation_finding_dto";
	__index = tenant_reputation_finding_dto;
}

local function cast_tenant_reputation_finding_dto(t)
	return setmetatable(t, tenant_reputation_finding_dto_mt)
end

local function new_tenant_reputation_finding_dto(account_region, tenant_name, tenant_arn, type, impact, status, description, created_timestamp, last_updated_timestamp)
	return cast_tenant_reputation_finding_dto({
		["accountRegion"] = account_region;
		["tenantName"] = tenant_name;
		["tenantArn"] = tenant_arn;
		["type"] = type;
		["impact"] = impact;
		["status"] = status;
		["description"] = description;
		["createdTimestamp"] = created_timestamp;
		["lastUpdatedTimestamp"] = last_updated_timestamp;
	})
end

return {
	cast = cast_tenant_reputation_finding_dto;
	new = new_tenant_reputation_finding_dto;
}
