--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- tracking_pixel_projection class
local tracking_pixel_projection = {}
local tracking_pixel_projection_mt = {
	__name = "tracking_pixel_projection";
	__index = tracking_pixel_projection;
}

local function cast_tracking_pixel_projection(t)
	return setmetatable(t, tracking_pixel_projection_mt)
end

local function new_tracking_pixel_projection(created_at, id, inbox_id, name, recipient, seen, seen_at, user_id)
	return cast_tracking_pixel_projection({
		["createdAt"] = created_at;
		["id"] = id;
		["inboxId"] = inbox_id;
		["name"] = name;
		["recipient"] = recipient;
		["seen"] = seen;
		["seenAt"] = seen_at;
		["userId"] = user_id;
	})
end

return {
	cast = cast_tracking_pixel_projection;
	new = new_tracking_pixel_projection;
}
