--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- tracking_pixel_dto class
local tracking_pixel_dto = {}
local tracking_pixel_dto_mt = {
	__name = "tracking_pixel_dto";
	__index = tracking_pixel_dto;
}

local function cast_tracking_pixel_dto(t)
	return setmetatable(t, tracking_pixel_dto_mt)
end

local function new_tracking_pixel_dto(id, seen, recipient, html, url, inbox_id, sent_email_id, seen_at, created_at)
	return cast_tracking_pixel_dto({
		["id"] = id;
		["seen"] = seen;
		["recipient"] = recipient;
		["html"] = html;
		["url"] = url;
		["inboxId"] = inbox_id;
		["sentEmailId"] = sent_email_id;
		["seenAt"] = seen_at;
		["createdAt"] = created_at;
	})
end

return {
	cast = cast_tracking_pixel_dto;
	new = new_tracking_pixel_dto;
}
