--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- update_smtp_access_options class
local update_smtp_access_options = {}
local update_smtp_access_options_mt = {
	__name = "update_smtp_access_options";
	__index = update_smtp_access_options;
}

local function cast_update_smtp_access_options(t)
	return setmetatable(t, update_smtp_access_options_mt)
end

local function new_update_smtp_access_options(smtp_username, smtp_password)
	return cast_update_smtp_access_options({
		["smtpUsername"] = smtp_username;
		["smtpPassword"] = smtp_password;
	})
end

return {
	cast = cast_update_smtp_access_options;
	new = new_update_smtp_access_options;
}
