--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- wait_for_sms_conditions class
local wait_for_sms_conditions = {}
local wait_for_sms_conditions_mt = {
	__name = "wait_for_sms_conditions";
	__index = wait_for_sms_conditions;
}

local function cast_wait_for_sms_conditions(t)
	return setmetatable(t, wait_for_sms_conditions_mt)
end

local function new_wait_for_sms_conditions(phone_number_id, limit, count, delay_timeout, timeout, unread_only, count_type, matches, sort_direction, since, before)
	return cast_wait_for_sms_conditions({
		["phoneNumberId"] = phone_number_id;
		["limit"] = limit;
		["count"] = count;
		["delayTimeout"] = delay_timeout;
		["timeout"] = timeout;
		["unreadOnly"] = unread_only;
		["countType"] = count_type;
		["matches"] = matches;
		["sortDirection"] = sort_direction;
		["since"] = since;
		["before"] = before;
	})
end

return {
	cast = cast_wait_for_sms_conditions;
	new = new_wait_for_sms_conditions;
}
