--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails from dynamically allocated email addresses. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://www.mailslurp.com/docs/) - [Examples](https://github.com/mailslurp/examples) repository 
 
  The version of the OpenAPI document: 6.5.2
  
  Generated by: https://openapi-generator.tech
]]

-- webhook_email_opened_payload class
local webhook_email_opened_payload = {}
local webhook_email_opened_payload_mt = {
	__name = "webhook_email_opened_payload";
	__index = webhook_email_opened_payload;
}

local function cast_webhook_email_opened_payload(t)
	return setmetatable(t, webhook_email_opened_payload_mt)
end

local function new_webhook_email_opened_payload(created_at, event_name, inbox_id, message_id, pixel_id, recipient, sent_email_id, webhook_id, webhook_name)
	return cast_webhook_email_opened_payload({
		["createdAt"] = created_at;
		["eventName"] = event_name;
		["inboxId"] = inbox_id;
		["messageId"] = message_id;
		["pixelId"] = pixel_id;
		["recipient"] = recipient;
		["sentEmailId"] = sent_email_id;
		["webhookId"] = webhook_id;
		["webhookName"] = webhook_name;
	})
end

return {
	cast = cast_webhook_email_opened_payload;
	new = new_webhook_email_opened_payload;
}
