--[[
  MailSlurp API
 
  MailSlurp is an API for sending and receiving emails and SMS from dynamically allocated email addresses and phone numbers. It's designed for developers and QA teams to test applications, process inbound emails, send templated notifications, attachments, and more.  ## Resources  - [Homepage](https://www.mailslurp.com) - Get an [API KEY](https://app.mailslurp.com/sign-up/) - Generated [SDK Clients](https://docs.mailslurp.com/) - [Examples](https://github.com/mailslurp/examples) repository
 
  The version of the OpenAPI document: 6.5.2
  Contact: contact@mailslurp.dev
  Generated by: https://openapi-generator.tech
]]

-- webhook_bounce_payload class
local webhook_bounce_payload = {}
local webhook_bounce_payload_mt = {
	__name = "webhook_bounce_payload";
	__index = webhook_bounce_payload;
}

local function cast_webhook_bounce_payload(t)
	return setmetatable(t, webhook_bounce_payload_mt)
end

local function new_webhook_bounce_payload(message_id, webhook_id, event_name, webhook_name, bounce_id, sent_to_recipients, sender, bounce_recipients)
	return cast_webhook_bounce_payload({
		["messageId"] = message_id;
		["webhookId"] = webhook_id;
		["eventName"] = event_name;
		["webhookName"] = webhook_name;
		["bounceId"] = bounce_id;
		["sentToRecipients"] = sent_to_recipients;
		["sender"] = sender;
		["bounceRecipients"] = bounce_recipients;
	})
end

return {
	cast = cast_webhook_bounce_payload;
	new = new_webhook_bounce_payload;
}
